### PR TITLE
Add documentation for Device POST and DELETE.

### PR DESCRIPTION
**Pull request by abdyer**
I added these endpoints to the Android core library and noticed we needed API docs.

### CODE REVIEW

**Comment by shadowhand** [comment]
Looks pretty good. Any comments @bvisness?

**Comment by bvisness** [comment]
@abdyer Did you mean for this example POST data to be alongside the "Create Device" section?

image

**Comment by bvisness** [comment]
The content looks really good! The only things I would suggest are to fix the formatting issue from above and to include example requests for Create Device as well.

I was going to also suggest that we include datatypes for all parameters under Create Device and Delete Device, but it looks like we don't really do that anywhere else in the docs.

**Comment by bvisness** [comment]
Oh, and a very minor quibble to make @shadowhand happy: http://chris.beams.io/posts/git-commit/#end

**Comment by shadowhand** [comment]
Thanks @bvisness :smile_cat:

**Comment by bvisness** [comment]
:+1:

**Pull request merged**
