### PR TITLE
Add place objects to account and location examples

### PR DESCRIPTION
**Pull request by th3fallen**
Probably shouldnt be merged until workplaces is activated for everyone though.

### CODE REVIEW

**Comment by shadowhand** [comment]
Thanks!

**Comment by shadowhand** [comment]
@th3fallen can you rebase this please?

**Comment by th3fallen** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by shadowhand** [comment]
onlydreams

**Comment by th3fallen** [comment]
@shadowhand works sooo much better when i rebase on docs and not master....

**Pull request merged**
